services:
  bbq-api-test:
    container_name: bbq-api-test
    build:
      context: ./bbq-api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./bbq-api:/app
    env_file:
      - ./bbq-api/.env
    networks:
      - main-network
    restart: unless-stopped

  bbq-frontend-test:
    container_name: bbq-frontend-test
    build:
      context: ./bbq-factory-os
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    networks:
      - main-network
    restart: unless-stopped

  mcp-postgres:
    container_name: mcp-postgres-server
    build:
      context: ./mcp-server
    env_file:
      - ./bbq-api/.env
    networks:
      - main-network
    restart: always

networks:
  main-network:
    external: true
